---
- hosts: webserver
  become: yes
  tasks:
  - name: Install prerequisites
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent' ,'software-properties-common', 'python-docker']
      update_cache: yes

  - name: Add docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add docker apt repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

  - name: Install docker
    apt:
      name: docker-ce
      update_cache: yes

  - name: Add user to group docker
    user:
      name: "{{ user }}"
      groups: docker
      append: yes

  vars_prompt:
  - name: user
    prompt: "Enter user to use docker without sudo"
    private: no

